apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cicd-pipeline-demo.fullname" . }}-env
  labels:
    {{- include "cicd-pipeline-demo.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
